# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Mapping the territory
tagline:             'Building castles in my mind'
description:         'Blog for my musing and aide-memoire'
url:                 https://davidssl.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              David Siew
  url:               https://davidssl.github.io
  email:             mynamewithoutspace_at_protonmail_dot_com

# Custom vars
version:             1.0.0